version: '3.9'

services:
  go_db:
    container_name: go_db
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=ABC123xyz
      - POSTGRES_USER=tux
      - POSTGRES_DB=db_loja
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
